# Generated by Django 6.1 on 2026-08-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_percent', models.PositiveIntegerField(help_text='Percentage discount, e.g. 15 for 15%')),
                ('max_discount', models.DecimalField(decimal_places=2, help_text='Maximum discount amount limit in INR', max_digits=10)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum purchase amount required', max_digits=10)),
                ('start_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('usage_limit', models.PositiveIntegerField(default=100, help_text='Total number of times this coupon can be used')),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
